var filters = {
  a: [],
  b: [
    "www.wikipedia.org",
    "www.redcross.org",
    "www.doctorswithoutborders.org",
    "redribbonfoundation.org",
    "www.cancer.org",
    "www.concern.net",
    "www.worldvision.org",
    "stackoverflow.com",
    "sourceforge.net",
    "www.linuxfoundation.org",
    "www.gnome.org",
    "www.kernel.org",
    "opensource.org",
    "github.com",
    "nrdc.org",
    "www.unicef.org",
    "www.openoffice.org",
    "www.libreoffice.org",
    "nodejs.org",
    "www.latex-project.org",
    "topaddon.com/firewall-lite"
  ],
  c: [
    "2mdn.net",
    "h2.msn.com/CIS",
    "spe.atdmt.com",
    "ads.contentabc.com/ads",
    "doubleclick.net",
    "mediaplex.com",
    "adserver.yahoo",
    "servedby.flashtalking",
    "tribalfusion.com",
    "pagead2.googlesyndication",
    "ads.adiquity",
    "admaster.union.ucweb",
    "dgeads.org",
    "ad120m.com",
    "fastclick.net",
    "kliksaya.com",
    "amazon-adsystem",
    "asset.flite.com",
    "adserver.adreactor",
    "ib.adnxs.com",
    "contextual.media.net",
    "ads.as4x.tmcs.ticketmaster",
    "msn.com/ADSAdClient",
    "revsci.net",
    "ads.celtra.com",
    "ads.exoclick",
    "adcash.com/script",
    "ads.openx",
    "mathtag.com",
    "ad.altervista.org",
    "ad.turn.com",
    "adsafeprotected.com",
    "ads.yahoo.",
    "showads.pubmatic",
    "adadvisor.net/adscores",
    "dl-rms.com",
    "bdv.bidvertiser.com/",
    "ad1.netshelter.net/adj",
    "js.adsonar.com/js/",
    "adserver.adtechus",
    "kona.kontera.com/javascript/",
    "google.com/aclk",
    "adwords.google.com",
    "mgid.com",
    "adforgames.com",
    "adnxs.com",
    "adsrvr.org",
    "union.ucweb",
    "googleadservices",
    "google.com/adsense",
    "clicks.beap.bc.yahoo",
    "beap.gemini.yahoo.com",
    "facebook.com/campaign/landing",
    "campaign/landing.php?placement",
    "ads.softonic.com",
    "softonicads.com/tracker",
    "turn.com/r/click",
    "go.padsdel.com",
    "ads.yesadvertising",
    "buysellads",
    "linkedin.com/ads/",
    "chitika.com",
    "chitika.net",
    "main.exoclick.com/click",
    "ads.digitalpoint",
    "ads.yldmgrimg.net",
    "cdn.betrad.com",
    "cdn.adfront.org",
    "clkrev.com",
    "padstm.com",
    "fast.cam.demdex.net",
    "fast.gm.demdex.net",
    "srcopenx.net",
    "4dsply.com",
    "openx.net",
    "ads.a-static",
    "cpmterra.com",
    "tpc.googlesyndication",
    "ads.as4x.tmcs.ticketmaster",
    "ads.qadservice",
    "betaffs.com",
    "syndication.exoclick.com",
    "google.com/uds/afs",
    "rocketadserver",
    "vindicosuite.com",
    "ads.cpxcenter",
    "ads.clicksor.com",
    "partnerads.ysm.yahoo",
    "cdn.cxense.com",
    "ad.anetwork",
    "ads.pubmatic",
    "cas.criteo",
    "linkedin.com/csp/ads",
    "syndication.globaltraffico.com/adserve",
    "syndication.traffichaus.com/adserve",
    "cdn.zeusclicks.com/ads/",
    "altare.sitescoutadserver",
    "ads.trafficjunky.net/ads",
    "bcp.crwdcntrl.net",
    "ad.kiosked",
    "ads.adsrvmedia.net",
    "doubleclick.com",
    "aimatch.com",
    "fbcdn-creative-a.akamaihd",
    "p.flite.com/p",
    "247realmedia",
    "exoclick.com/banners",
    "adzerk.net",
    "struq.com",
    "dotomi.com",
    "advertising.com",
    "padsdel.cdnads",
    "bs.serving-sys",
    "static.fl-ads.com/Advertisers",
    "engine.fl-ads",
    "cdn.cdntraffic.com/ads",
    "sscdn.banners.advidi",
    "static.dreamsadnetwork",
    "banners.sexypartners",
    "rpc-php.trafficfactory.biz",
    "banners.sexypartners",
    "syndication.cntrafficpro",
    "ads.trafficjunky",
    "sscdn.banners.advidi",
    "media.trafficfactory.biz",
    "cdn.betrad.com"
  ],
  d: [],
  e: [],
  get adblockList() {
    return this.a;
  },
  set adblockList(value) {
    this.a = value;
  },
  get allowedURLs() {
    return this.b;
  },
  set allowedURLs(value) {
    this.b = value;
  },
  get blockedURLs() {
    return this.c;
  },
  set blockedURLs(value) {
    this.c = value;
  },
  get scriptList() {
    return this.d;
  },
  set scriptList(value) {
    this.d = value;
  },
  get adServer() {
    return this.e;
  },
  set adServer(value) {
    this.e = value;
  }
 };

 /* Blocked and Allowed URLs */
if (typeof require !== 'undefined') { // for Firefox
  exports.filters = filters;
}